repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=1000']

  - repo: https://github.com/hadialqattan/pycln
    rev: v2.2.1
    hooks:
      - id: pycln
        language_version: python3

  - repo: local
    hooks:
      - id: build-minified-assets
        name: Build minified assets
        entry: node build.js
        language: system
        types: [javascript, css]
        stages: [commit]
